dynamixels: ['dynamixel_AX12_17_joint', 'dynamixel_AX12_6_joint']

dynamixel_AX12_17_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: dynamixel_AX12_17_joint
    joint_speed: 2.0
    motor:
        id: 17
        init: 512
        min: 0
        max: 1024

dynamixel_AX12_6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: dynamixel_AX12_6_joint
    joint_speed: 2.0
    motor:
        id: 6
        init: 512
        min: 300
        max: 800
