<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dog_picker_leg">
  <xacro:include filename="$(find dynamixel_description)/urdf/constants.xacro"/>
  <xacro:include filename="$(find dynamixel_description)/urdf/AX12.xacro"/>
  <xacro:macro name="dog_picker_leg_right" params="parent dyn1 dyn2 dyn3 x_loc y_loc z_loc r p y back">
    <joint name="robotis_part_${dyn1}" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="${r+90*M_PI/180} ${p+-90*M_PI/180} ${y+back*M_PI}"/>
      <parent link="${parent}"/>
      <child link="dynamixel_AX12_${dyn1}_link"/>
    </joint>
    <xacro:dynamixel_AX12_down number="${dyn1}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0" y="0"/>
    <!-- this fixed joint is really just placing the revolute joint in the next ax12 that way I can just always pass 0 to ax12-->
    <joint name="S1_${dyn1}" type="fixed">
      <origin xyz="${-AX12_Z_SIZE-2*AX12_Z_CENTER} ${-AX12_X_SIZE/2 - F7_Z_SIZE}  ${AX12_Y_CENTER}" rpy="${-90*M_PI/180} 0 ${90*M_PI/180} "/>
      <parent link="S-B_${dyn1}_link"/>
      <child link="dynamixel_AX12_${dyn2}_link"/>
    </joint>
    <xacro:dynamixel_AX12_down number="${dyn2}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0"  y="0"/>
      <joint name="S1_${dyn2}" type="fixed">
      <origin xyz="0 ${F2_Y_CENTER} ${F2_Z_SIZE-F2_Z_CENTER}" rpy="0 0 0"/>
      <parent link="S-B_${dyn2}_link"/>
      <child link="calf_link_${dyn3}"/>
    </joint>
    <link name="calf_link_${dyn3}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${F2_X_SIZE}  ${F2_Y_SIZE} ${F2_Z_SIZE*2}"/>
        </geometry>
        <material name="DimWhite">
          <color rgba="0.9 0.9 0.9 1.0"/>
        </material>
      </visual>
    </link>
      <joint name="S1_${dyn3}" type="fixed">
      <origin xyz="0 ${-F2_Y_CENTER} ${F2_Z_SIZE-F2_Z_CENTER}" rpy="0 ${180*M_PI/180} 0"/>
      <parent link="calf_link_${dyn3}"/>
      <child link="S-B_${dyn3}_link"/>
    </joint>    
    <xacro:dynamixel_AX12_up number="${dyn3}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0" y="0"/>
  </xacro:macro>
  
  
  <xacro:macro name="dog_picker_leg_left" params="parent dyn1 dyn2 dyn3 x_loc y_loc z_loc r p y back">
    <joint name="robotis_part_${dyn1}" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="${r+-90*M_PI/180} ${p+90*M_PI/180} ${y+back*M_PI}"/>
      <parent link="${parent}"/>
      <child link="dynamixel_AX12_${dyn1}_link"/>
    </joint>
    
      <xacro:dynamixel_AX12_down number="${dyn1}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0" y="0"/>
    <!-- this fixed joint is really just placing the revolute joint in the next ax12 that way I can just always pass 0 to ax12-->
    <joint name="S1_${dyn1}" type="fixed">
      <origin xyz="${AX12_Z_SIZE+2*AX12_Z_CENTER} ${-AX12_X_SIZE/2 - F7_Z_SIZE}  ${AX12_Y_CENTER}" rpy="${-90*M_PI/180} 0 ${-90*M_PI/180} "/>
      <parent link="S-B_${dyn1}_link"/>
      <child link="dynamixel_AX12_${dyn2}_link"/>
    </joint>
    <xacro:dynamixel_AX12_down number="${dyn2}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0"  y="0"/>
      <joint name="S1_${dyn2}" type="fixed">
      <origin xyz="0 ${F2_Y_CENTER} ${F2_Z_SIZE-F2_Z_CENTER}" rpy="0 0 0"/>
      <parent link="S-B_${dyn2}_link"/>
      <child link="calf_link_${dyn3}"/>
    </joint>
    <link name="calf_link_${dyn3}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="${F2_X_SIZE}  ${F2_Y_SIZE} ${F2_Z_SIZE*2}"/>
        </geometry>
        <material name="DimWhite">
          <color rgba="0.9 0.9 0.9 1.0"/>
        </material>
      </visual>
    </link>
      <joint name="S1_${dyn3}" type="fixed">
      <origin xyz="0 ${-F2_Y_CENTER} ${F2_Z_SIZE-F2_Z_CENTER}" rpy="0 ${180*M_PI/180} 0"/>
      <parent link="calf_link_${dyn3}"/>
      <child link="S-B_${dyn3}_link"/>
    </joint>    
    <xacro:dynamixel_AX12_up number="${dyn3}" x_loc="0" y_loc="0" z_loc="0" r="0" p="0" y="0"/>
  </xacro:macro>  
</robot>

