controller_list:
  - name: fake_right_front_leg_controller
    joints:
      - dynamixel_AX12_4_joint
      - dynamixel_AX12_16_joint
      - dynamixel_AX12_8_joint
  - name: fake_left_front_leg_controller
    joints:
      - dynamixel_AX12_5_joint
      - dynamixel_AX12_7_joint
      - dynamixel_AX12_9_joint
  - name: fake_back_right_leg_controller
    joints:
      - dynamixel_AX12_10_joint
      - dynamixel_AX12_12_joint
      - dynamixel_AX12_14_joint
  - name: fake_back_left_leg_controller
    joints:
      - dynamixel_AX12_11_joint
      - dynamixel_AX12_13_joint
      - dynamixel_AX12_15_joint
  - name: fake_head_neck_controller
    joints:
      - dynamixel_AX12_6_joint
      - dynamixel_AX12_17_joint
  - name: fake_back_butt_controller
    joints:
      - virtual_joint
      - dynamixel_AX12_1_joint